# This rule is not used by the project kube-ebpf-monitor itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over ebpf.monitoring.dev.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kube-ebpf-monitor
    app.kubernetes.io/managed-by: kustomize
  name: ebpfdaemonset-admin-role
rules:
- apiGroups:
  - ebpf.monitoring.dev
  resources:
  - ebpfdaemonsets
  verbs:
  - '*'
- apiGroups:
  - ebpf.monitoring.dev
  resources:
  - ebpfdaemonsets/status
  verbs:
  - get
