apiVersion: ebpf.monitoring.dev/v1alpha1
kind: EbpfDaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-ebpf-monitor
    app.kubernetes.io/managed-by: kustomize
  name: ebpfdaemonset-sample
spec:
  image: alejandrosalamanca17/knative-example-native:latest
  nodeSelector:
    kubernetes.io/os: linux
  resources:
    limits:
      cpu: "600m"
      memory: "256Mi"
    requests:
      cpu: "100m"
      memory: "128Mi"
  runPrivileged: true
