apiVersion: ebpf.monitoring.dev/v1alpha1
kind: EbpfDaemonSet
metadata:
  labels:
    app.kubernetes.io/name: kube-ebpf-monitor
    app.kubernetes.io/managed-by: kustomize
  name: ebpfdaemonset-sample
spec:
  image: alejandrosalamanca17/ebpf-loader:latest
  nodeSelector:
    kubernetes.io/os: linux 
  enableProbes:
    - open
    - execve
  serverPort: "8080"
  serverAddress: 10.0.0.1
